name: 'Deploy'
on: [push]
description: 'Build image using docker and deploy to Cloud Foundry'
env:
  CF_URL: teste
  CF_USER: teste
  CF_PASSWORD: 'teste'
  CF_DEV_ORG: teste
  CF_DEV_SPACE: teste
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - CF_URL=${{ env.CF_URL }}
    - CF_USER=${{ env.CF_USER }}
    - CF_PASSWORD=${{ env.CF_PASSWORD }}
    - CF_DEV_ORG=${{ env.CF_DEV_ORG }}
    - CF_DEV_SPACE=${{ env.CF_DEV_SPACE }}