name: 'Deploy'
description: 'Build image using docker and deploy to Cloud Foundry'
inputs:
  cfUrl:
    required: true
    description: 'Url of Cloud Foundry'
  cfUser:
    required: true
    description: 'Login to Cloud Foundry'
  cfPassword:
    required: true
    description: 'Cloud Foundry password'
  cfDevOrg:
    required: true
    description: 'Cloud Foundry Dev Org'
  cfDevSpace:
    required: true
    description: 'Cloud Foundry Dev Space'
runs:
  using: 'composite'
  steps:
    - id: build
      run: docker build . --build-arg CF_URL="${{ inputs.cfUrl }}" --build-arg CF_USER="${{ inputs.cfUser }}" --build-arg CF_PASSWORD='${{ inputs.cfPassword }}' --build-arg CF_DEV_ORG="${{ inputs.cfDevOrg }}" --build-arg=CF_DEV_SPACE="${{ inputs.cfDevSpace }}" -t micro-rankings
      shell: bash 