name: 'Deploy'
description: 'Build image using docker and deploy to Cloud Foundry'
inputs:
  cfUrl:
    required: true
    description: 'Url of Cloud Foundry'
  cfUser:
    required: true
    description: 'Login to Cloud Foundry'
  cfPassword:
    required: true
    description: 'Cloud Foundry password'
  cfDevOrg:
    required: true
    description: 'Cloud Foundry Dev Org'
  cfDevSpace:
    required: true
    description: 'Cloud Foundry Dev Space'
runs:
  using: 'composite'
  steps:
    - id: build
      run: docker build . --build-arg CF_URL="https://api.cf.us10.hana.ondemand.com" --build-arg CF_USER="danillo.moraes@outlook.com" --build-arg CF_PASSWORD='$V6Z7TU4#dq*?GX' --build-arg CF_DEV_ORG="3c5b9327trial" --build-arg=CF_DEV_SPACE="dev" -t micro-rankings
      shell: bash
  #using: 'docker'
  #image: 'Dockerfile'
  #env:
  #  -CF_URL: ${{ inputs.cfUrl }}
  #  -CF_USER: ${{ inputs.cfUser }}
  #  -CF_PASSWORD: ${{ inputs.cfPassword }}
  #  -CF_DEV_ORG: ${{ inputs.cfDevOrg }}
  #  -CF_DEV_SPACE: ${{ inputs.cfDevSpace }}